### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by Karotte128** [MisterJulsen/Create-Train-Navigator#17]
Hi!

I have some questions/ideas about units in this mod.

- units "kmh" and similar are wrong. It has to be "km/h"

- Maybe add blocks/second as another speed unit.

This mod is really cool btw.

**Comment by MisterJulsen** [comment]
Thanks for your feedback! The units are only wrong in the config, as I have a very limited number of characters available there. However, the units are displayed correctly in the game.
blocks/second already exists in a slightly different form: m/s (Config Value: ms). Since a block in Minecraft has the size of one meter, no further unit is required.
